# Site settings
title: Carl Domingo
description: "So, you've found yourself on my personal blog page? Here, I hope to enlighten minds about cool tips and tricks for coding and life in general."
baseurl: ""
url: "http://cdomingo.github.io"

# Owner information
owner:
 name: Carl
 full_name: Carl Domingo
 avatar: 
 bio:  
 email: carl.m.domingo@gmail.com
 # Social networking links are used in author-bio sidebar. Update and remove as you like.
 twitter: carlflamingo      
 facebook: 
 github: cdomingo    
 linkedin:
 instagram: carlflamingo 

# Build settings
timezone: America/New_York
markdown: kramdown
permalink: pretty
