# Site settings
title: Carl Blog-mingo
description: "So, you've found yourself on my personal blog page? Here, I hope to enlighten minds about cool tips and tricks for coding and life in general."
baseurl: ""
url: "http://cdomingo.github.io"

# Owner information
owner:
 name: Carl
 full_name: Carl Domingo
 avatar: https://lh6.googleusercontent.com/-4dHo4OTlGzI/UpLJ7VWXrhI/AAAAAAAAADE/NItAvkFhvgw/w830-h834-no/CarlHeadShot.jpg
 email: carl.m.domingo@gmail.com
 website: http://cdomingo.com/
 # Social networking links are used in author-bio sidebar. Update and remove as you like.
 twitter: carlflamingo
 github: cdomingo    
 linkedin: carldomingo

# Build settings
timezone: America/New_York
markdown: kramdown
permalink: pretty
